BEGIN;
-- Часовые ставки из таблицы партнёра, ключ «город + тип вакансии».
-- Замер 03.09.2026. Вахта не трогается: значения там уже стоят.
UPDATE vacancies AS v
SET salary_hour = s.rate
FROM (VALUES
  ('kurer-lenta-krasnodar-velo-moto', 224),
  ('kurer-lenta-anapa-avto', 100),
  ('kurer-lenta-novorossiysk-avto', 100),
  ('kurer-lenta-obninsk-avto', 209.23),
  ('kurer-lenta-saransk-avto', 132),
  ('kurer-lenta-tambov-avto', 104.8),
  ('kurer-lenta-tyumen-avto', 83),
  ('kurer-lenta-astrahan-velo', 156),
  ('kurer-lenta-volgograd-velo', 173),
  ('kurer-lenta-volzhskiy-velo', 152),
  ('kurer-lenta-ekaterinburg-velo', 224),
  ('kurer-lenta-izhevsk-velo', 180),
  ('kurer-lenta-irkutsk-velo', 230),
  ('kurer-lenta-kamensk-uralskiy-velo', 139),
  ('kurer-lenta-krasnoyarsk-velo', 195.2),
  ('kurer-lenta-lipeck-velo', 194),
  ('kurer-lenta-novokuzneck-velo', 184),
  ('kurer-lenta-rostov-na-donu-velo', 227),
  ('kurer-lenta-samara-velo', 78),
  ('kurer-lenta-rostov-na-donu-moto', 227),
  ('sborshchik-lenta-velikiy-novgorod', 143),
  ('sborshchik-lenta-ekaterinburg', 180),
  ('sborshchik-lenta-zheleznovodsk', 166),
  ('sborshchik-lenta-irkutsk', 193),
  ('sborshchik-lenta-kursk', 146),
  ('sborshchik-lenta-lipeck', 122),
  ('sborshchik-lenta-moskva', 207),
  ('sborshchik-lenta-murmansk', 230),
  ('sborshchik-lenta-nefteyugansk', 227),
  ('sborshchik-lenta-nizhnekamsk', 139),
  ('sborshchik-lenta-novosibirsk', 178),
  ('sborshchik-lenta-novoshahtinsk', 135),
  ('sborshchik-lenta-obninsk', 223),
  ('sborshchik-lenta-omsk', 154),
  ('sborshchik-lenta-perm', 160),
  ('sborshchik-lenta-rostov-na-donu', 205),
  ('sborshchik-lenta-samara', 153),
  ('sborshchik-lenta-sankt-peterburg', 226),
  ('sborshchik-lenta-saransk', 142),
  ('sborshchik-lenta-tomsk', 148),
  ('sborshchik-lenta-ulyanovsk', 134),
  ('sborshchik-lenta-hanty-mansiysk', 224),
  ('kurer-samokat-velikiy-novgorod-velo', 105),
  ('kurer-samokat-ekaterinburg-velo', 110),
  ('kurer-samokat-izhevsk-velo', 125),
  ('kurer-samokat-moskva-velo', 105),
  ('kurer-samokat-nizhniy-tagil-velo', 110),
  ('kurer-samokat-noginsk-velo', 105),
  ('kurer-samokat-orel-velo', 110),
  ('kurer-samokat-sankt-peterburg-velo', 105),
  ('kurer-samokat-smolensk-velo', 100),
  ('kurer-samokat-tambov-velo', 115),
  ('kurer-samokat-tver-velo', 100),
  ('kurer-samokat-tomsk-velo', 130),
  ('kurer-samokat-tula-velo', 110),
  ('kurer-samokat-cheboksary-velo', 135),
  ('kurer-samokat-chelyabinsk-velo', 120),
  ('kurer-samokat-engels-velo', 110),
  ('kurer-samokat-velikiy-novgorod-evelo', 125),
  ('kurer-samokat-ekaterinburg-evelo', 130),
  ('kurer-samokat-izhevsk-evelo', 135),
  ('kurer-samokat-moskva-evelo', 105),
  ('kurer-samokat-nizhniy-tagil-evelo', 130),
  ('kurer-samokat-noginsk-evelo', 130),
  ('kurer-samokat-sankt-peterburg-evelo', 125),
  ('kurer-samokat-smolensk-evelo', 120),
  ('kurer-samokat-tambov-evelo', 135),
  ('kurer-samokat-tver-evelo', 120),
  ('kurer-samokat-tomsk-evelo', 130),
  ('kurer-samokat-tula-evelo', 130),
  ('kurer-samokat-cheboksary-evelo', 160)
) AS s(slug, rate)
WHERE v.slug = s.slug AND v.salary_hour IS NULL;
COMMIT;
