BEGIN;
-- Адреса точек Ленты — только там, где город обслуживает один склад.
-- Пишем только в пустые: не перезаписываем 10 уже заполненных вахтовых.
UPDATE vacancies AS v
SET address = s.address
FROM (VALUES
  ('kurer-lenta-kamensk-uralskiy-largus', 'Суворова ул., 48'),
  ('kurer-lenta-novocherkassk-largus', 'Гагарина ул., 2Б'),
  ('kurer-lenta-novoshahtinsk-largus', 'Харьковская ул., 201'),
  ('kurer-lenta-krasnodar-velo-moto', 'ул. Восточный обход, 19'),
  ('kurer-lenta-almetevsk-avto', 'Ленина ул., 132'),
  ('kurer-lenta-anapa-avto', 'г. Анапа ул. Привокзальная, д.8'),
  ('kurer-lenta-balakovo-avto', 'Комарова ул., 117'),
  ('kurer-lenta-bratsk-avto', 'Гагарина ул., 75'),
  ('kurer-lenta-velikiy-novgorod-avto', 'Псковская ул., 33'),
  ('kurer-lenta-voronezh-avto', 'Воронеж, Московский проспект, 129/1'),
  ('kurer-lenta-ekaterinburg-avto', 'проспект Академика Сахарова, 107/1'),
  ('kurer-lenta-ivanovo-avto', 'Карла Маркса ул., 3'),
  ('kurer-lenta-irkutsk-avto', 'Сергеева ул., 3/5, ТЦ Сильвер Молл'),
  ('kurer-lenta-kaluga-avto', 'Грабцевское ш., 59'),
  ('kurer-lenta-kamensk-uralskiy-avto', 'Суворова ул., 48'),
  ('kurer-lenta-kemerovo-avto', 'Баумана ул., 20'),
  ('kurer-lenta-krasnoyarsk-avto', 'Свердловская ул., 73'),
  ('kurer-lenta-kurgan-avto', 'Коли Мяготина ул., 8, ТЦ ГиперСити'),
  ('kurer-lenta-kursk-avto', 'Энгельса ул., 115Д'),
  ('kurer-lenta-magnitogorsk-avto', 'Ленина ул., 119, ТЦ Тетрис'),
  ('kurer-lenta-maykop-avto', 'Степная ул., 190, ТЦ Майкоп - Молл'),
  ('kurer-lenta-naberezhnye-chelny-avto', 'Набережночелнинский проспект, 13А'),
  ('kurer-lenta-nizhnekamsk-avto', 'Лесная ул., 14'),
  ('kurer-lenta-nizhniy-tagil-avto', 'Уральский пр,75, Свердловское ш. 31'),
  ('kurer-lenta-novorossiysk-avto', 'Григорьева ул., 1'),
  ('kurer-lenta-novocherkassk-avto', 'Гагарина ул., 2Б'),
  ('kurer-lenta-orel-avto', 'Московское шоссе, 56'),
  ('kurer-lenta-petrozavodsk-avto', 'Ленинградская ул., 13'),
  ('kurer-lenta-pskov-avto', 'Труда ул., 54'),
  ('kurer-lenta-ryazan-avto', 'Тимуровцев ул., 3а'),
  ('kurer-lenta-saransk-avto', 'Волгоградская ул., 71, ТЦ Сити-Парк'),
  ('kurer-lenta-saratov-avto', 'Верхняя ул., 17, корпус 1'),
  ('kurer-lenta-stavropol-avto', 'Доваторцев ул., 75А, ТЦ Космос'),
  ('kurer-lenta-sterlitamak-avto', 'Худайбердина ул., 120, ТЦ Фабри'),
  ('kurer-lenta-surgut-avto', 'Югорский тракт, 2'),
  ('kurer-lenta-syktyvkar-avto', 'Сысольское ш., 27'),
  ('kurer-lenta-taganrog-avto', 'Большая Бульварная ул., 15, ТЦ Парус'),
  ('kurer-lenta-tambov-avto', 'г. Тамбов, ул. Чичерина, д.3.'),
  ('kurer-lenta-tver-avto', 'Московское ш., 16/3'),
  ('kurer-lenta-ulan-ude-avto', 'пр-кт. Автомобилистов, д. 4а1 ТЦ Capital Mall'),
  ('kurer-lenta-hanty-mansiysk-avto', 'Объездная ул., 9'),
  ('kurer-lenta-engels-avto', 'Красноярская ул., 5Б'),
  ('kurer-lenta-volgograd-velo', 'Пролетарская ул., 8'),
  ('kurer-lenta-volzhskiy-velo', 'Проспект имени Ленина 313'),
  ('kurer-lenta-irkutsk-velo', 'Сергеева ул., 3/5, ТЦ Сильвер Молл'),
  ('kurer-lenta-kamensk-uralskiy-velo', 'Суворова ул., 48'),
  ('kurer-lenta-novokuzneck-velo', 'Транспортная ул.136'),
  ('kurer-lenta-rostov-na-donu-velo', 'ул. Аксайский пр., 2'),
  ('kurer-lenta-novorossiysk-moto', 'Григорьева ул., 1'),
  ('kurer-lenta-rostov-na-donu-moto', 'ул. Аксайский пр., 2'),
  ('sborshchik-lenta-velikiy-novgorod', 'Псковская ул., 33'),
  ('sborshchik-lenta-zheleznovodsk', 'Геологическая ул., 29'),
  ('sborshchik-lenta-kursk', 'Энгельса ул., 115Д'),
  ('sborshchik-lenta-lipeck', 'Катукова ул., 51, ТЦ Ривьера'),
  ('sborshchik-lenta-nizhnekamsk', 'Лесная ул., 14'),
  ('sborshchik-lenta-novoshahtinsk', 'Харьковская ул., 201'),
  ('sborshchik-lenta-perm', 'Героев Хасана ул., 105, ТЦ Шоколад'),
  ('sborshchik-lenta-saransk', 'Волгоградская ул., 71, ТЦ Сити-Парк'),
  ('sborshchik-lenta-tomsk', 'Елизаровых ул., 13'),
  ('sborshchik-lenta-hanty-mansiysk', 'Объездная ул., 9')
) AS s(slug, address)
WHERE v.slug = s.slug AND v.address IS NULL;
COMMIT;
